In [1]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(' 2 and 3')
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print('223')
print(x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([7.1107e+31])
tensor([1.2244e-37, 3.0813e-41, 1.2282e-37])
tensor([[1.1341e+36, 4.5786e-41, 1.1341e+36],
        [4.5786e-41, 4.4842e-44, 0.0000e+00]])
tensor([[[1.2271e-37, 3.0813e-41, 1.2121e-37],
         [3.0813e-41, 6.3010e-36, 6.3010e-36]],

        [[6.3010e-36, 6.3010e-36, 1.0571e-28],
         [2.5809e-32, 2.9058e-17, 1.6131e-33]]])
tensor([[0.0847, 0.9456, 0.2189],
        [0.4281, 0.4898, 0.7509],
        [0.1219, 0.3231, 0.4918],
        [0.7466, 0.6823, 0.2289],
        [0.2786, 0.0455, 0.2798]])
